# B-S 評價

In [1]:
from scipy.stats import norm
from math import sqrt, exp, log

def BS(X):
    d1 = (log(S / K) + (R + Sigma * Sigma/2) * T) / (Sigma * sqrt(T))
    d2 = d1 - Sigma * sqrt(T)

    if X == 'C':
        return S * norm.cdf(d1) - K * exp(-R * T) * norm.cdf(d2)
    if X == 'P':
        return K * exp(-R * T) * norm.cdf(-d2) - S * norm.cdf(-d1)
    
def main():
    global S, T, R, K, Sigma

    S = 100
    K = 100
    Sigma = 0.3
    R = 0.01
    T = 1

    print('The price of Call = %.15f' %BS('C'))
    print('The price of Put  = %.15f' %BS('P'))

main()

The price of Call = 12.368267463784079
The price of Put  = 11.373250838700891


# 二分法解函數

In [2]:
def f(x):
    return pow(x, 2) - 2

def solve():
    a = 1
    b = 2

    while True:
        c = (b + a)/ 2
        
        if b - c < pow(10, -6):
            break

        if f(b) * f(c) < 0:
            a = c
        else:
            b = c
    return c

def main():
    print('函數求解 %.6f' %solve())

main()

函數求解 1.414214


#   二分法解BS model 隱含波動率

In [3]:
def BS(X, Sigma):
    d1 = (log(S / K) + (R + Sigma * Sigma/2) * T) / (Sigma * sqrt(T))
    d2 = d1 - Sigma * sqrt(T)

    if X == 'C':
        return S * norm.cdf(d1) - K * exp(-R * T) * norm.cdf(d2) - Price_C
    if X == 'P':
        return K * exp(-R * T) * norm.cdf(-d2) - S * norm.cdf(-d1) - Price_P
    
def solve(X):
    a = 0.00001
    b = 1.00001

    while True:
        c = (b + a)/ 2
        
        if b - c < pow(10, -15):
            break

        if BS(X, b) * BS(X, c) < 0:
            a = c
        else:
            b = c
    return c

def main():
    global S, T, R, K, Price_C, Price_P

    S = 100
    K = 100
    # Sigma = 0.3
    R = 0.01
    T = 1

    Price_C = 12.368267463784079
    Price_P = 11.373250838700891

    print('IV of Call = %.15f' %solve('C'))
    print('IV of Put  = %.15f' % solve('P'))

main()

IV of Call = 0.300000000000000
IV of Put  = 0.300000000000000


# Iris MLP 教學

In [4]:
#!/usr/bin/env python
# -*- coding=utf-8 -*-
__author__ = "柯博文老師 Powen Ko, www.powenko.com"

from sklearn import datasets
from sklearn.model_selection import train_test_split
import tensorflow as tf
import numpy as np
import pandas as pd


iris = datasets.load_iris()

category=3
dim=4
x_train , x_test , y_train , y_test = train_test_split(iris.data,iris.target,test_size=0.2)
y_train2=tf.keras.utils.to_categorical(y_train, num_classes=(category))
y_test2=tf.keras.utils.to_categorical(y_test, num_classes=(category))

print("x_train[:4]",x_train[:4])
print("y_train[:4]",y_train[:4])
print("y_train2[:4]",y_train2[:4])

# 建立模型
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=10,
    activation=tf.nn.relu,
    input_dim=dim))
model.add(tf.keras.layers.Dense(units=10,
    activation=tf.nn.relu ))
model.add(tf.keras.layers.Dense(units=category,
    activation=tf.nn.softmax ))
model.compile(optimizer='adam',
    loss=tf.keras.losses.categorical_crossentropy,
    metrics=['accuracy'])

model.fit(x_train, y_train2,
          epochs=250,
          batch_size=16)

#測試
score = model.evaluate(x_test, y_test2, batch_size=16)
print("score:",score)

x_train[:4] [[4.7 3.2 1.3 0.2]
 [6.7 2.5 5.8 1.8]
 [6.3 2.9 5.6 1.8]
 [5.7 3.  4.2 1.2]]
y_train[:4] [0 2 2 1]
y_train2[:4] [[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]]
Epoch 1/250


/Users/xinc./Library/Python/3.9/lib/python/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 807us/step - accuracy: 0.3309 - loss: 1.8764
Epoch 2/250
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 456us/step - accuracy: 0.3517 - loss: 1.5296
Epoch 3/250
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 505us/step - accuracy: 0.6875 - loss: 1.2251
Epoch 4/250
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 496us/step - accuracy: 0.6908 - loss: 1.1426
Epoch 5/250
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 621us/step - accuracy: 0.6100 - loss: 1.2866
Epoch 6/250
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 700us/step - accuracy: 0.6875 - loss: 1.0014
Epoch 7/250
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 759us/step - accuracy: 0.6800 - loss: 0.9676
Epoch 8/250
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 728us/step - accuracy: 0.6955 - loss: 0.8798
Epoch 9/250
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - accuracy: 0.6660 - loss: 0.8942
Epoch 10/250
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 661us/step - accuracy: 0.6835 - loss: 0.8241
Epoch 11/250
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 501us/step - accuracy: 0.6647 - loss: 0.8023
Epoch 12/250
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 462us/step - accuracy: 0.6946 - lo

In [5]:
predict = model.predict(x_test)
# print('Ans:', np.argmax(predict[0]), np.argmax(predict[1]), np.argmax(predict[2]), np.argmax(predict[3]))

predict2 = model.predict(x_test)
predict2 = np.argmax(predict2, axis = 1)
# print('predict_classes:', predict2)
# print('y_test', y_test[:])

sum = 0
Iris = pd.DataFrame(columns = ['預測', '答案'])
Iris.index.name = '編號'

for i in range(len(y_test)):
    Iris.loc['%5d' %i] = [predict2[i], y_test[i]]
    if predict2[i] == y_test[i]:
        sum += 1

print(Iris)
    
print('準確率 = %.6f' %(sum/len(y_test)))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step
    預測  答案
編號        
 0   0   0
 1   0   0
 2   0   0
 3   2   1
 4   0   0
 5   1   1
 6   0   0
 7   1   1
 8   2   2
 9   2   2
10   2   2
11   1   1
12   0   0
13   1   1
14   1   1
15   0   0
16   2   2
17   1   1
18   1   1
19   0   0
20   1   1
21   0   0
22   2   2
23   2   2
24   0   0
25   1   1
26   1   1
27   2   2
28   2   2
29   1   1
準確率 = 0.966667
